### ISSUE TITLE
Part 5: not mentioning modification in op_precedence()

### ISSUE THREAD

**Issue by Psycho7** [DoctorWkt/acwj#12]
The following 2 lines are updated based on the use of `;`
https://github.com/DoctorWkt/acwj/blob/ba9c5ba676078b04b9caa87d38cc862bbfbf0d49/05_Statements/expr.c#L72
https://github.com/DoctorWkt/acwj/blob/ba9c5ba676078b04b9caa87d38cc862bbfbf0d49/05_Statements/expr.c#L92

It's better to mention that otherwise may take some time for reader to find the issue

**Comment by DoctorWkt** [comment]
Thanks Chujie Zeng for the suggestion. I have updated the Readme for part 5 with some comments on the change to the parser.
