### ISSUE TITLE
Issue with function call arguments that are themselves function calls

### ISSUE THREAD

**Issue by luke-gru** [DoctorWkt/acwj#13]
Hi, first off I want to say thank you for all the work you've put into this project. I've been following along in my spare time, made it to the end of the book, and have thoroughly enjoyed it. I've added a few features of my own like varargs `...` arguments, anonymous unions inside structs, more robust support for '++' and '--' operators (like `s.var++` and `++s.var`).

In adding these features and changing the codebase, I've uncovered a little issue. Take this example code:

```c
#include <stdio.h>

int mycall(int a, int b, int c, int d, int e) {
  return (1);
}

int main(void) {
  int i;
  i = 10;
  /**
  * Bug in output of next line. Naive solution:
   * for every argument node that contains a function call, we push all argument
   * registers to the stack before generating asm for the call and pop them off after.
   */
  printf("%d, %d, %d\n", i, mycall(1, 2, 3, 4, 5), i); // expect: 10,1,10, got 10,1,4
  return (0);
}
```

Running this gives improper output as the call to `mycall` clobbers the argument register `rcx` used to store the value of the 4th parameter to `printf`.

I could send a PR but I expect my codebase differs from yours to a large extent now, so it would be easier for you to patch this your way than it would be for me to port the patch over.

Thanks again 😃

**Comment by DoctorWkt** [comment]
Thanks for the feedback and bug reports, Luke. I've just started my teaching work again, so a bit less time, but I should be able to close these issues over the next week. I'll probably look at what you've done and borrow some of your code. Cheers, Warren
