### ISSUE TITLE
Issue with negative integer scanning

### ISSUE THREAD

**Issue by luke-gru** [DoctorWkt/acwj#15]
Hi again 😺 

You're probably aware of this already, but the scanner is too eager with scanning the '-' character as being part of an integer instead of an operand. For example:

```c
#include <stdio.h>

int main() {
  printf("%d\n",1-1); // can't parse this, as scanner scans this as 2 consecutive T_INTLITs
  return (0);
}
```
Thanks,

**Comment by DoctorWkt** [comment]
Thanks for the heads-up. I've put a note about it in [](https://github.com/DoctorWkt/acwj/tree/master/43_More_Operators), but I'll leave it unfixed.
