### ISSUE TITLE
Part 7: register's b-suffix not mentioned in doc

### ISSUE THREAD

**Issue by Psycho7** [DoctorWkt/acwj#16]
The variable `breglist` is declared here but not mentioned, and just shows up from nowhere in the doc.

https://github.com/DoctorWkt/acwj/blob/b11b269c71727297b367203eaed164364291db16/07_Comparisons/cg.c#L13

IMO it would better to mention the `b-suffix` somewhere before `breglist` appears in the journey.

**Comment by DoctorWkt** [comment]
Yes, that's an excellent suggestion. I've just made some changes to describe the register names and the breglist[]. Thanks, Warren
