### ISSUE TITLE
prerequisite knowledge

### ISSUE THREAD

**Issue by samwulol** [DoctorWkt/acwj#22]
Thank you for sharing your course. I am sophomore student,what prerequisite knowledge should i have?

**Comment by DoctorWkt** [comment]
You should have a working knowledge of a programming language like C, Java, Python. You should have at least an introductory knowledge of how C works, especially with structures and pointers. That's about it. Maybe something like this [introduction to C](https://www.cs.rochester.edu/u/ferguson/csc/c/c-for-java-programmers.pdf) would be good to read.
