### ISSUE TITLE
Question about void type compatibility

### ISSUE THREAD

**Issue by cloudrex** [DoctorWkt/acwj#3]
Under the context of https://github.com/DoctorWkt/acwj/tree/master/12_Types_pt1#building-binary-expressions-comparing-types:

```
...
// Same types, they are compatible
  if (*left == *right) { *left = *right = 0; return (1);
  }
  // Voids not compatible with anything
  if ((*left == P_VOID) || (*right == P_VOID)) return (0);
...
```
What if `left == right` and left/right is `void`? Isn't void incompatible with anything (including itself)?

**Comment by DoctorWkt** [comment]
Yes, well spotted. I've rearranged the code to have the void test first. Thanks, Warren
