### ISSUE TITLE
why not return 1 directly?

### ISSUE THREAD

**Issue by logerrors** [DoctorWkt/acwj#33]
I notice that some function will return (1) ,not return 1,why do that?
![CleanShot 2020-12-20 at 20 36 52@2x](https://user-images.githubusercontent.com/31824303/102713437-351d2f00-4303-11eb-9b7e-21d974a89a90.png)

**Comment by Itai-Nelken** [comment]
it doesn't matter, its the same.

**Comment by DoctorWkt** [comment]
It makes the parsing easier to parse only return(x) instead of both return(x) and return x.
Cheers!
