### ISSUE TITLE
 Can i repost project to my blog?

### ISSUE THREAD

**Issue by Shaw9379** [DoctorWkt/acwj#37]
Hello, I am a developer from China. 
Now, i am  following your project to study. 
I like your project very much. 
Excuse me, can I translate and repost your project to my blog. 
Looking forward to your reply. 
Thanks !

**Comment by DoctorWkt** [comment]
Yes, you can definitely do this.
Cheers, Warren

**Comment by Shaw9379** [comment]
Thank you very much
