### ISSUE TITLE
Is there a reason that a lot of things are statically allocated rather than dynamically allocated?

### ISSUE THREAD

**Issue by Jachdich** [DoctorWkt/acwj#41]
For example, the global symbol table has a max number of entries, I've been implementing everything dynamically and `realloc`ing as necessary, however I am worried that I have missed some important reason for statically allocating memory.

**Comment by DoctorWkt** [comment]
There's no specific reason except that I wanted to keep the code as simple as possible. The aim of the compiler is to educate, not to be a production compiler! Thanks for the comment, though.

**Comment by Jachdich** [comment]
Ah that makes sense. Thank you for clearing that up
