### ISSUE TITLE
Why you don't put books in 00 Intro?

### ISSUE THREAD

**Issue by ponyatov** [DoctorWkt/acwj#6]
Dragon and Tiger/C books are the first ones I think about while anybody speaks about compiler implementing.

The advantage of Appel's book is the presence of the manual on using Boehm GC which will be required while we step forward from core C to other languages.

https://www.cs.princeton.edu/~appel/modern/c/

**Comment by DoctorWkt** [comment]
I changed the Readme to mention books in Ahmad Alhour's Curated list of awesome resources on Compilers, Interpreters and Runtimes. Most books are heavy on the theory; my repository tries to be light on the theory. Thanks for the suggestion.
