### ISSUE TITLE
The whole language bnf grammar

### ISSUE THREAD

**Issue by BlankHeart0** [DoctorWkt/acwj#67]
Where is the whole bnf grammar？I need it, thank you! Maybe I am not carefully enough to find it ...

**Comment by DoctorWkt** [comment]
I didn't do a BNF grammar for the language that `acwj` recognises, sorry.  There is a BNF for the full C language at [https://www.lysator.liu.se/c/ANSI-C-grammar-y.html](https://www.lysator.liu.se/c/ANSI-C-grammar-y.html)

**Comment by BlankHeart0** [comment]
Ok, Thank you !
