### ISSUE TITLE
FYI: ApolloVM - A Multilingual portable VM with on-the-fly Wasm compilation.

### ISSUE THREAD

**Issue by gmpassos** [DoctorWkt/acwj#68]
Firstly,

Thanks for the interesting project, especially for documenting it.

It's not easy to find developers who like to build compilers.

You might find this project interesting:
https://github.com/ApolloVM/apollovm_dart

I am currently in the process of developing the memory allocator that will be employed for object allocation when ApolloVM [compiles to WebAssembly](https://github.com/ApolloVM/apollovm_dart#wasm-support).

Best regards.

**Comment by ravenleeblack** [comment]
This is unrelated to the current project and should be closed.
