### ISSUE TITLE
Unnecessary Return

### ISSUE THREAD

**Issue by L4B0MB4** [DoctorWkt/acwj#8]
First of all: Not really a big deal ;) Just needed some extra time to understand what is going on:

```c
// Return an AST tree whose root is a '+' or '-' binary operator
struct ASTnode *additive_expr(void) {
  struct ASTnode *left, *right;
  int tokentype;
  // Get the left sub-tree at a higher precedence than us
  left = multiplicative_expr();
  // If no tokens left, return just the left node
  tokentype = Token.token;
  if (tokentype == T_EOF)
    return (left);
  // Loop working on token at our level of precedence
  while (1) {
    // Fetch in the next integer literal
    scan(&Token);
    // Get the right sub-tree at a higher precedence than us
    right = multiplicative_expr();
    // Join the two sub-trees with our low-precedence operator
    left = mkastnode(arithop(tokentype), left, right, 0);
    // And get the next token at our precedence
    tokentype = Token.token;
    if (tokentype == T_EOF)
      return (left);
  }

  // Return whatever tree we have created
  return (left);
}
```
From: https://github.com/DoctorWkt/acwj/tree/master/03_Precedence

I think the last return is never reached because the condition in the while loop is always true and there is nothing else that should trigger a break. 

Why I am creating an issue: Maybe I am wrong and there is something that would trigger a break. Just want to double check 

PS: Really nice guide overall ! Thanks a lot

**Comment by DoctorWkt** [comment]
Well spotted. I've refactored the additive and multiplicative loops. Thanks, Warren
